path_to_micro_waypoints:
  ros__parameters:
    input_path_topic: /generated_path
    spacing: 0.2
    micro_waypoints_topic: /micro_waypoints
    micro_waypoints_path_topic: /micro_waypoints_path
    marker_topic: /micro_waypoints_marker
    marker_scale: 0.08
