frenet_skid_mpc:
  ros__parameters:
    path_topic: /micro_waypoints_path
    vref_topic: /v_ref
    cmdvel_topic: /cmd_vel
    base_frame: base_link

    rate_hz: 6.0
    dt: 0.12
    N: 10

    v_nom: 0.18
    v_max: 0.22
    r_max: 1.6
